In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset = {
    "x" : [5,7,8,7,2,17,2,9,4,11,12,9,6],
    "y" : [99,86,87,88,111,86,103,87,94,78,77,85,86]
}

In [4]:
df = pd.DataFrame(dataset)

In [5]:
X = df.iloc[:, 0].values
X = X.reshape(-1,1)
X

array([[ 5],
       [ 7],
       [ 8],
       [ 7],
       [ 2],
       [17],
       [ 2],
       [ 9],
       [ 4],
       [11],
       [12],
       [ 9],
       [ 6]], dtype=int64)

In [6]:
y = df.iloc[:, -1].values
y

array([ 99,  86,  87,  88, 111,  86, 103,  87,  94,  78,  77,  85,  86],
      dtype=int64)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
model = LinearRegression()

In [9]:
model.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred = model.predict(X_test)

In [12]:
y_pred

array([83.54460094, 77.58215962, 95.46948357, 98.45070423, 59.69483568])

In [13]:
r2 = r2_score(y_test, y_pred)

In [14]:
r2

-1.698840123501737

In [15]:
mean_squared_error(y_test, y_pred)

145.30555224933354